version: '3'

services:
  app:
    build: 
      context: node
    container_name: app
    networks:
      - desafio-nginx
    ports:
      - "8080:8080"

networks:
  desafio-nginx:
    driver: bridge
