version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - banco:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - desafio-nginx

  app:
    build: 
      context: ./node
      dockerfile: Dockerfile
    container_name: app
    tty: true
    networks:
      - desafio-nginx
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:
      build:
        context: ./nginx
        dockerfile: Dockerfile
      container_name: nginx
      networks:
        - desafio-nginx
      ports:
        - "8080:80"
      depends_on:
        - app

networks:
  desafio-nginx:
    driver: bridge

volumes:
  banco: