version: '3'

services:
  app:
    build: 
      context: ./node
      dockerfile: Dockerfile
    container_name: app
    tty: true
    networks:
      - desafio-nginx
    ports:
      - "3000:3000"

networks:
  desafio-nginx:
    driver: bridge
